services:
  node:
    container_name: node
    image: node:20
    working_dir: /scrivo
    volumes:
      - ./scrivo:/scrivo
    ports:
      - "3003:3000"
    command: npm run dev

  latex:
    container_name: latex
    volumes:
      - ./scrivo:/scrivo
    build:
      context: ./docker/latex
      dockerfile: ./Dockerfile
